const cfg = require("../configs/config.json");
const { MessageEmbed } = require("discord.js");
const moment = require("moment");
const client = global.client;
const Discord = require("discord.js");
const StreamerDatabase = require("../schemas/Streamer");

module.exports = async (oldState, newState) => {
 
  try{let StreamerData = await StreamerDatabase.findOne({ guildID: newState.member.guild.id, userID: newState.member.id})
  const Log = new Discord.WebhookClient(cfg.Webhook.VoiceLogWebhook.ID, cfg.Webhook.VoiceLogWebhook.Token);
  let date = `${moment(Date.now()).format("DD")} ${moment(Date.now()).format("MM").replace("01", "Ocak").replace("02", "Şubat").replace("03", "Mart").replace("04", "Nisan").replace("05", "Mayıs").replace("06", "Haziran").replace("07", "Temmuz").replace("08", "Ağustos").replace("09", "Eylül").replace("10", "Ekim").replace("11", "Kasım").replace("12", "Aralık")} ${moment(Date.now()).format("YYYY")} ${moment(Date.now()).format("HH:mm")}`;
  if (!oldState.channelID && newState.channelID) {
  Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Sesli Kanala Katılma\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nSesli Kanala Giriş: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136)) 
  }
  if (oldState.channelID && !newState.channelID) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Sesli Kanaldan Ayrılma\`\n\n```Kanal: "+newState.guild.channels.cache.get(oldState.channelID).name+" ("+oldState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nSesli Kanaldan Ayrılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (oldState.channelID && newState.channelID && oldState.channelID != newState.channelID) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Ses Kanalı Değiştirme\`\n\n```Eski Kanal: "+oldState.guild.channels.cache.get(oldState.channelID).name+" ("+oldState.channelID+")\nYeni Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nKanal Değiştiriliş: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (oldState.channelID && oldState.selfMute && !newState.selfMute) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Susturma Kaldırıldı\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nSusturma Kaldırılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (oldState.channelID && !oldState.selfMute && newState.selfMute) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Susturma\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nSusturma Atılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (oldState.channelID && oldState.selfDeaf && !newState.selfDeaf) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Sağırlaştırma Kaldırıldı\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nSağırlaştırma Kaldırılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (oldState.channelID && !oldState.selfDeaf && newState.selfDeaf) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Sağırlaştırma\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nSağırlaştırma Atılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (oldState.channelID && !oldState.selfDeaf && newState.selfDeaf) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Sağırlaştırma\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nSağırlaştırma Atılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (newState.member.voice.streaming === true) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Yayın Açma\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nYayın Açılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  if (StreamerData) {
  if (newState.member.voice.streaming === false) {Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Yayın Kapandı\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nYayın Kapanış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  }return}
  if (newState.member.voice.selfVideo === true) return Log.send(new MessageEmbed().setThumbnail(newState.member.user.avatarURL({dynamic:true})).setDescription("<@!"+newState.guild.members.cache.get(newState.id)+"> üyesine sesli kanalda bir işlem uygulandı.\n\n **__Uygulanan İşlem__:** \`Kamera Açma\`\n\n```Kanal: "+newState.guild.channels.cache.get(newState.channelID).name+" ("+newState.channelID+")\nKullanıcı: "+newState.member.user.tag+" ("+newState.id+")\nKamera Açılış: "+date+"```").setAuthor(newState.member.user.tag, newState.member.user.avatarURL({dynamic:true})).setColor(0x2F3136))
  }catch{{}}
}
module.exports.conf = {
  name: "voiceStateUpdate"
};
